// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_server

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ServerResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_tokens": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Sensitive:           true,
				Description:         "List of API tokens associated with server.",
				MarkdownDescription: "List of API tokens associated with server.",
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
			},
			"color": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Color of the server in the server list, for quick identification. Possible values - 'purple', 'blue', 'turquoise', 'green', 'red', 'yellow', 'grey', 'orange'",
				MarkdownDescription: "Color of the server in the server list, for quick identification. Possible values - 'purple', 'blue', 'turquoise', 'green', 'red', 'yellow', 'grey', 'orange'",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf(
						"purple",
						"blue",
						"turquoise",
						"green",
						"red",
						"yellow",
						"orange",
						"grey",
					),
				},
			},
			"delivery_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Specifies the type of environment for your server. Possible options - Live Sandbox. Defaults to Live if not specified. This cannot be changed after the server has been created.",
				MarkdownDescription: "Specifies the type of environment for your server. Possible options - Live Sandbox. Defaults to Live if not specified. This cannot be changed after the server has been created.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"Live",
						"Sandbox",
					),
				},
				Default: stringdefault.StaticString("Live"),
			},
			"enable_smtp_api_error_hooks": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Specifies whether or not SMTP API Errors will be included with bounce webhooks.",
				MarkdownDescription: "Specifies whether or not SMTP API Errors will be included with bounce webhooks.",
				Default:             booldefault.StaticBool(false),
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID of server",
				MarkdownDescription: "ID of server",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"inbound_address": schema.StringAttribute{
				Computed:            true,
				Description:         "Inbound email address",
				MarkdownDescription: "Inbound email address",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"inbound_domain": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Inbound domain for MX setup.",
				MarkdownDescription: "Inbound domain for MX setup.",
				Default:             stringdefault.StaticString(""),
			},
			"inbound_hash": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				Description:         "The inbound hash of your inbound email address.",
				MarkdownDescription: "The inbound hash of your inbound email address.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"inbound_hook_url": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "URL to POST to every time an inbound event occurs.",
				MarkdownDescription: "URL to POST to every time an inbound event occurs.",
				Default:             stringdefault.StaticString(""),
			},
			"inbound_spam_threshold": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The maximum spam score for an inbound message before it's blocked.",
				MarkdownDescription: "The maximum spam score for an inbound message before it's blocked.",
				Default:             int64default.StaticInt64(0),
			},
			"include_bounce_content_in_hook": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Include bounce content in webhook.",
				MarkdownDescription: "Include bounce content in webhook.",
				Default:             booldefault.StaticBool(false),
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Server name",
				MarkdownDescription: "Server name",
			},
			"post_first_open_only": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If set to true, only the first open by a particular recipient will initiate the open webhook. Any subsequent opens of the same email by the same recipient will not initiate the webhook.",
				MarkdownDescription: "If set to true, only the first open by a particular recipient will initiate the open webhook. Any subsequent opens of the same email by the same recipient will not initiate the webhook.",
				Default:             booldefault.StaticBool(false),
			},
			"raw_email_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When enabled, the raw email content will be included with inbound webhook payloads under the RawEmail key.",
				MarkdownDescription: "When enabled, the raw email content will be included with inbound webhook payloads under the RawEmail key.",
				Default:             booldefault.StaticBool(false),
			},
			"server_link": schema.StringAttribute{
				Computed:            true,
				Description:         "URL to your server overview page in Postmark.",
				MarkdownDescription: "URL to your server overview page in Postmark.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"smtp_api_activated": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Specifies whether or not SMTP is enabled on this server.",
				MarkdownDescription: "Specifies whether or not SMTP is enabled on this server.",
				Default:             booldefault.StaticBool(false),
			},
			"track_links": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates if all emails being sent through this server should have link tracking enabled for links in their HTML or Text bodies. Possible options - 'None', 'HtmlAndText', 'HtmlOnly', 'TextOnly'",
				MarkdownDescription: "Indicates if all emails being sent through this server should have link tracking enabled for links in their HTML or Text bodies. Possible options - 'None', 'HtmlAndText', 'HtmlOnly', 'TextOnly'",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"None",
						"HtmlAndText",
						"HtmlOnly",
						"TextOnly",
					),
				},
				Default: stringdefault.StaticString("None"),
			},
			"track_opens": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates if all emails being sent through this server have open tracking enabled.",
				MarkdownDescription: "Indicates if all emails being sent through this server have open tracking enabled.",
				Default:             booldefault.StaticBool(false),
			},
		},
	}
}

type ServerModel struct {
	ApiTokens                  types.List   `tfsdk:"api_tokens"`
	Color                      types.String `tfsdk:"color"`
	DeliveryType               types.String `tfsdk:"delivery_type"`
	EnableSmtpApiErrorHooks    types.Bool   `tfsdk:"enable_smtp_api_error_hooks"`
	Id                         types.String `tfsdk:"id"`
	InboundAddress             types.String `tfsdk:"inbound_address"`
	InboundDomain              types.String `tfsdk:"inbound_domain"`
	InboundHash                types.String `tfsdk:"inbound_hash"`
	InboundHookUrl             types.String `tfsdk:"inbound_hook_url"`
	InboundSpamThreshold       types.Int64  `tfsdk:"inbound_spam_threshold"`
	IncludeBounceContentInHook types.Bool   `tfsdk:"include_bounce_content_in_hook"`
	Name                       types.String `tfsdk:"name"`
	PostFirstOpenOnly          types.Bool   `tfsdk:"post_first_open_only"`
	RawEmailEnabled            types.Bool   `tfsdk:"raw_email_enabled"`
	ServerLink                 types.String `tfsdk:"server_link"`
	SmtpApiActivated           types.Bool   `tfsdk:"smtp_api_activated"`
	TrackLinks                 types.String `tfsdk:"track_links"`
	TrackOpens                 types.Bool   `tfsdk:"track_opens"`
}
