// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_server

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ServerDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_tokens": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"color": schema.StringAttribute{
				Computed: true,
			},
			"delivery_type": schema.StringAttribute{
				Computed: true,
			},
			"enable_smtp_api_error_hooks": schema.BoolAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"inbound_address": schema.StringAttribute{
				Computed: true,
			},
			"inbound_domain": schema.StringAttribute{
				Computed: true,
			},
			"inbound_hash": schema.StringAttribute{
				Computed: true,
			},
			"inbound_hook_url": schema.StringAttribute{
				Computed: true,
			},
			"inbound_spam_threshold": schema.Int64Attribute{
				Computed: true,
			},
			"include_bounce_content_in_hook": schema.BoolAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"post_first_open_only": schema.BoolAttribute{
				Computed: true,
			},
			"raw_email_enabled": schema.BoolAttribute{
				Computed: true,
			},
			"server_link": schema.StringAttribute{
				Computed: true,
			},
			"smtp_api_activated": schema.BoolAttribute{
				Computed: true,
			},
			"track_links": schema.StringAttribute{
				Computed: true,
			},
			"track_opens": schema.BoolAttribute{
				Computed: true,
			},
		},
	}
}

type ServerModel struct {
	ApiTokens                  types.List   `tfsdk:"api_tokens"`
	Color                      types.String `tfsdk:"color"`
	DeliveryType               types.String `tfsdk:"delivery_type"`
	EnableSmtpApiErrorHooks    types.Bool   `tfsdk:"enable_smtp_api_error_hooks"`
	Id                         types.String `tfsdk:"id"`
	InboundAddress             types.String `tfsdk:"inbound_address"`
	InboundDomain              types.String `tfsdk:"inbound_domain"`
	InboundHash                types.String `tfsdk:"inbound_hash"`
	InboundHookUrl             types.String `tfsdk:"inbound_hook_url"`
	InboundSpamThreshold       types.Int64  `tfsdk:"inbound_spam_threshold"`
	IncludeBounceContentInHook types.Bool   `tfsdk:"include_bounce_content_in_hook"`
	Name                       types.String `tfsdk:"name"`
	PostFirstOpenOnly          types.Bool   `tfsdk:"post_first_open_only"`
	RawEmailEnabled            types.Bool   `tfsdk:"raw_email_enabled"`
	ServerLink                 types.String `tfsdk:"server_link"`
	SmtpApiActivated           types.Bool   `tfsdk:"smtp_api_activated"`
	TrackLinks                 types.String `tfsdk:"track_links"`
	TrackOpens                 types.Bool   `tfsdk:"track_opens"`
}
