// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_postmark

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func PostmarkProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_token": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "The Account API token to use for API requests. Managed at https://account.postmarkapp.com/api_tokens.",
				MarkdownDescription: "The Account API token to use for API requests. Managed at https://account.postmarkapp.com/api_tokens.",
			},
		},
	}
}

type PostmarkModel struct {
	AccountToken types.String `tfsdk:"account_token"`
}
