// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_domain

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func DomainDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"dkimhost": schema.StringAttribute{
				Computed: true,
			},
			"dkimpending_host": schema.StringAttribute{
				Computed: true,
			},
			"dkimpending_text_value": schema.StringAttribute{
				Computed: true,
			},
			"dkimrevoked_host": schema.StringAttribute{
				Computed: true,
			},
			"dkimrevoked_text_value": schema.StringAttribute{
				Computed: true,
			},
			"dkimtest_value": schema.StringAttribute{
				Computed: true,
			},
			"dkimupdate_status": schema.StringAttribute{
				Computed: true,
			},
			"dkimverified": schema.BoolAttribute{
				Computed: true,
			},
			"domainid": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID for the Domain that should be retrieved.",
				MarkdownDescription: "The ID for the Domain that should be retrieved.",
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"return_path_domain": schema.StringAttribute{
				Computed: true,
			},
			"return_path_domain_cnamevalue": schema.StringAttribute{
				Computed: true,
			},
			"return_path_domain_verified": schema.BoolAttribute{
				Computed: true,
			},
			"safe_to_remove_revoked_key_from_dns": schema.BoolAttribute{
				Computed: true,
			},
			"spfhost": schema.StringAttribute{
				Computed: true,
			},
			"spftext_value": schema.StringAttribute{
				Computed: true,
			},
			"spfverified": schema.BoolAttribute{
				Computed: true,
			},
			"weak_dkim": schema.BoolAttribute{
				Computed: true,
			},
		},
	}
}

type DomainModel struct {
	Dkimhost                      types.String `tfsdk:"dkimhost"`
	DkimpendingHost               types.String `tfsdk:"dkimpending_host"`
	DkimpendingTextValue          types.String `tfsdk:"dkimpending_text_value"`
	DkimrevokedHost               types.String `tfsdk:"dkimrevoked_host"`
	DkimrevokedTextValue          types.String `tfsdk:"dkimrevoked_text_value"`
	DkimtestValue                 types.String `tfsdk:"dkimtest_value"`
	DkimupdateStatus              types.String `tfsdk:"dkimupdate_status"`
	Dkimverified                  types.Bool   `tfsdk:"dkimverified"`
	Domainid                      types.Int64  `tfsdk:"domainid"`
	Id                            types.String `tfsdk:"id"`
	Name                          types.String `tfsdk:"name"`
	ReturnPathDomain              types.String `tfsdk:"return_path_domain"`
	ReturnPathDomainCnamevalue    types.String `tfsdk:"return_path_domain_cnamevalue"`
	ReturnPathDomainVerified      types.Bool   `tfsdk:"return_path_domain_verified"`
	SafeToRemoveRevokedKeyFromDns types.Bool   `tfsdk:"safe_to_remove_revoked_key_from_dns"`
	Spfhost                       types.String `tfsdk:"spfhost"`
	SpftextValue                  types.String `tfsdk:"spftext_value"`
	Spfverified                   types.Bool   `tfsdk:"spfverified"`
	WeakDkim                      types.Bool   `tfsdk:"weak_dkim"`
}
