// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_sender_signature

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SenderSignatureResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"confirmed": schema.BoolAttribute{
				Computed: true,
			},
			"dkimhost": schema.StringAttribute{
				Computed: true,
			},
			"dkimpending_host": schema.StringAttribute{
				Computed: true,
			},
			"dkimpending_text_value": schema.StringAttribute{
				Computed: true,
			},
			"dkimrevoked_host": schema.StringAttribute{
				Computed: true,
			},
			"dkimrevoked_text_value": schema.StringAttribute{
				Computed: true,
			},
			"dkimtest_value": schema.StringAttribute{
				Computed: true,
			},
			"dkimupdate_status": schema.StringAttribute{
				Computed: true,
			},
			"dkimverified": schema.BoolAttribute{
				Computed: true,
			},
			"domain": schema.StringAttribute{
				Computed: true,
			},
			"email_address": schema.StringAttribute{
				Computed: true,
			},
			"from_email": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "From email associated with sender signature.",
				MarkdownDescription: "From email associated with sender signature.",
			},
			"id": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "From name associated with sender signature.",
				MarkdownDescription: "From name associated with sender signature.",
			},
			"reply_to_email": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Override for reply-to address.",
				MarkdownDescription: "Override for reply-to address.",
			},
			"reply_to_email_address": schema.StringAttribute{
				Computed: true,
			},
			"return_path_domain": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A custom value for the Return-Path domain. It is an optional field, but it must be a subdomain of your From Email domain and must have a CNAME record that points to pm.mtasv.net.",
				MarkdownDescription: "A custom value for the Return-Path domain. It is an optional field, but it must be a subdomain of your From Email domain and must have a CNAME record that points to pm.mtasv.net.",
			},
			"return_path_domain_cnamevalue": schema.StringAttribute{
				Computed: true,
			},
			"return_path_domain_verified": schema.BoolAttribute{
				Computed: true,
			},
			"safe_to_remove_revoked_key_from_dns": schema.BoolAttribute{
				Computed: true,
			},
			"signatureid": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The ID for the Sender Signature that should be retrieved.",
				MarkdownDescription: "The ID for the Sender Signature that should be retrieved.",
			},
			"spfhost": schema.StringAttribute{
				Computed: true,
			},
			"spftext_value": schema.StringAttribute{
				Computed: true,
			},
			"spfverified": schema.BoolAttribute{
				Computed: true,
			},
			"weak_dkim": schema.BoolAttribute{
				Computed: true,
			},
		},
	}
}

type SenderSignatureModel struct {
	Confirmed                     types.Bool   `tfsdk:"confirmed"`
	Dkimhost                      types.String `tfsdk:"dkimhost"`
	DkimpendingHost               types.String `tfsdk:"dkimpending_host"`
	DkimpendingTextValue          types.String `tfsdk:"dkimpending_text_value"`
	DkimrevokedHost               types.String `tfsdk:"dkimrevoked_host"`
	DkimrevokedTextValue          types.String `tfsdk:"dkimrevoked_text_value"`
	DkimtestValue                 types.String `tfsdk:"dkimtest_value"`
	DkimupdateStatus              types.String `tfsdk:"dkimupdate_status"`
	Dkimverified                  types.Bool   `tfsdk:"dkimverified"`
	Domain                        types.String `tfsdk:"domain"`
	EmailAddress                  types.String `tfsdk:"email_address"`
	FromEmail                     types.String `tfsdk:"from_email"`
	Id                            types.Int64  `tfsdk:"id"`
	Name                          types.String `tfsdk:"name"`
	ReplyToEmail                  types.String `tfsdk:"reply_to_email"`
	ReplyToEmailAddress           types.String `tfsdk:"reply_to_email_address"`
	ReturnPathDomain              types.String `tfsdk:"return_path_domain"`
	ReturnPathDomainCnamevalue    types.String `tfsdk:"return_path_domain_cnamevalue"`
	ReturnPathDomainVerified      types.Bool   `tfsdk:"return_path_domain_verified"`
	SafeToRemoveRevokedKeyFromDns types.Bool   `tfsdk:"safe_to_remove_revoked_key_from_dns"`
	Signatureid                   types.Int64  `tfsdk:"signatureid"`
	Spfhost                       types.String `tfsdk:"spfhost"`
	SpftextValue                  types.String `tfsdk:"spftext_value"`
	Spfverified                   types.Bool   `tfsdk:"spfverified"`
	WeakDkim                      types.Bool   `tfsdk:"weak_dkim"`
}
